version : "3"

networks:
  test:
    external:
      name: test
services: 
  nodeapp:
    deploy:
      placement:
        constraints:
            - node.labels.name == manager
    image: coe-dinus/node-app:latest
    ports :
      - 4000:4000
    networks:
      test:
        aliases:
          - nodeapp