# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: "3"

networks:
  test:
    external:
      name: test

services:
  ca_petani:
    deploy:
      placement:
        constraints:
          - node.labels.name == manager
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-petani
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - /home/ubuntu/hlf-docker-swarm/test-network/organizations/fabric-ca/petani:/etc/hyperledger/fabric-ca-server
    container_name: ca_petani
    networks:
       test:
         aliases:
          - ca.petani.coedinus.com

  ca_pengepul:
    deploy:
      placement:
        constraints:
          - node.labels.name == worker1
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-pengepul
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - /home/ubuntu/hlf-docker-swarm/test-network/organizations/fabric-ca/pengepul:/etc/hyperledger/fabric-ca-server
    container_name: ca_pengepul
    networks:
       test:
         aliases:
          - ca.pengepul.coedinus.com

  ca_distributor:
    deploy:
      placement:
        constraints:
          - node.labels.name == worker2
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-distributor
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=9054
    ports:
      - "9054:9054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - /home/ubuntu/hlf-docker-swarm/test-network/organizations/fabric-ca/distributor:/etc/hyperledger/fabric-ca-server
    container_name: ca_distributor
    networks:
       test:
         aliases:
          - ca.distributor.coedinus.com

  ca_retailer:
    deploy:
      placement:
        constraints:
          - node.labels.name == worker3
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-retailer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=11054
    ports:
      - "11054:11054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - /home/ubuntu/hlf-docker-swarm/test-network/organizations/fabric-ca/retailer:/etc/hyperledger/fabric-ca-server
    container_name: ca_retailer
    networks:
       test:
         aliases:
          - ca.retailer.coedinus.com

  ca_orderer:
    deploy:
      placement:
        constraints:
          - node.labels.name == manager
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-orderer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=10054
    ports:
      - "10054:10054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - /home/ubuntu/hlf-docker-swarm/test-network/organizations/fabric-ca/ordererOrg:/etc/hyperledger/fabric-ca-server
    container_name: ca_orderer
    networks:
       test:
         aliases:
          - ca.orderer.coedinus.com
